<a href="https://colab.research.google.com/github/HelloSamved/learning-neural-network/blob/master/pytorch/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


##Introduction to Tensors
###creating tensors

Pytorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/2.12/tensors.html

In [2]:
##Introduction to Tensors:
#Creating tensors

In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#convert tensor back to integer
scalar.item()

7

In [6]:
#Vector:
vector= torch.tensor([10,7])
vector

tensor([10,  7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#####We can think of dimension as number of square brackets while defining inside torch.tensor()
#####And Shape depends on order which is for our vector is (2x1)

In [9]:
#Create a matrix:
MATRIX= torch.tensor([[1,2],[2,3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Create a tensor:
TENSOR= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Here 1 means that we got one (3x3) matrix

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR1= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1,3,5],
                        [2,4,6],
                        [7,8,9]]])

In [17]:
TENSOR1.ndim

3

In [18]:
TENSOR1.shape

torch.Size([2, 3, 3])

###Random tensors

##Random Tensors
####Why Random Tensors?
####Random tensors are important because they way neural network learn is that they start with tensors full numbers and then adjust those random numbers to better represent the data.

###The flow looks like:
####Start with random numbers in tensor --> look at data --> update random numbers --> look at data --> (loop)

In [19]:
#Create a random tensor of size:
random_tensor1= torch.rand(1,10,10)
random_tensor1

tensor([[[0.0845, 0.9561, 0.7500, 0.4519, 0.5223, 0.5624, 0.0781, 0.4918,
          0.1193, 0.2501],
         [0.3302, 0.4668, 0.9106, 0.3941, 0.5299, 0.1497, 0.4538, 0.2980,
          0.9046, 0.9952],
         [0.9899, 0.4101, 0.1946, 0.8534, 0.7517, 0.2737, 0.3616, 0.3923,
          0.8892, 0.7025],
         [0.8661, 0.8067, 0.2296, 0.7236, 0.0722, 0.1389, 0.2303, 0.7960,
          0.2601, 0.9885],
         [0.7662, 0.4107, 0.8313, 0.1979, 0.1565, 0.6499, 0.7488, 0.5192,
          0.1576, 0.4783],
         [0.9639, 0.5966, 0.7038, 0.3721, 0.4834, 0.5754, 0.0525, 0.2802,
          0.8671, 0.8152],
         [0.5467, 0.8451, 0.4128, 0.8483, 0.8653, 0.5418, 0.5684, 0.1056,
          0.8977, 0.5361],
         [0.4771, 0.4134, 0.2942, 0.1224, 0.8679, 0.6813, 0.4385, 0.2922,
          0.7892, 0.4677],
         [0.3961, 0.4197, 0.0556, 0.1769, 0.8119, 0.6997, 0.1061, 0.5175,
          0.4980, 0.1398],
         [0.2994, 0.2471, 0.6450, 0.1964, 0.5651, 0.6812, 0.0505, 0.4725,
          0.7887,

In [20]:
random_tensor1.shape

torch.Size([1, 10, 10])

In [21]:
random_tensor2= torch.rand(4,10,10)
random_tensor2

tensor([[[0.3336, 0.5867, 0.3452, 0.1093, 0.1226, 0.1554, 0.3742, 0.2260,
          0.1517, 0.4435],
         [0.8929, 0.3307, 0.1433, 0.1048, 0.7290, 0.5572, 0.4958, 0.6805,
          0.3728, 0.9011],
         [0.2017, 0.6937, 0.1864, 0.2132, 0.5649, 0.6782, 0.1191, 0.6620,
          0.2589, 0.5886],
         [0.0285, 0.5508, 0.6539, 0.1785, 0.9046, 0.2660, 0.6620, 0.0299,
          0.3227, 0.7122],
         [0.0846, 0.7026, 0.1566, 0.7397, 0.3105, 0.3942, 0.2926, 0.1557,
          0.1340, 0.1293],
         [0.0825, 0.0424, 0.7973, 0.3471, 0.5120, 0.8153, 0.9612, 0.8732,
          0.7042, 0.3412],
         [0.1683, 0.2737, 0.4008, 0.8849, 0.7500, 0.0613, 0.9378, 0.6817,
          0.6606, 0.3486],
         [0.2507, 0.9035, 0.0175, 0.6531, 0.5469, 0.0042, 0.7002, 0.6441,
          0.1362, 0.5392],
         [0.7570, 0.4989, 0.6590, 0.5225, 0.1522, 0.9136, 0.2353, 0.9510,
          0.8419, 0.8567],
         [0.6712, 0.6634, 0.6641, 0.8048, 0.0576, 0.4827, 0.4100, 0.7976,
          0.2721,

In [22]:
random_tensor2.shape, random_tensor2.ndim

(torch.Size([4, 10, 10]), 3)

In [23]:
#Random tensor with similar shape to an image:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

##Zeroes and Ones

In [24]:
#Create a tensor with only zeroes:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create a tensor with only ones:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors like

In [26]:
#Use torch.arange()
one_to_ten=torch.arange(start=1, end= 100, step=5)
one_to_ten

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [27]:
one_to_ten.shape, one_to_ten.ndim

(torch.Size([20]), 1)

In [28]:
#Creating tensors like:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Data Types

In [29]:
#Float 32 Type:
float_32_tensor= torch.tensor([1.0,2.0,3.0],
                               dtype=None, #this defines the data type of the tensor, here none will set it dtype as float32 by default
                               device= None, #
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [30]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [31]:
#Just Experimenting
x= float_32_tensor* float_16_tensor
x

tensor([1., 4., 9.])

In [32]:
x.dtype

torch.float32

In [33]:
int_32_tensor= torch.tensor([1,2,3], dtype= torch.long)
int_32_tensor

tensor([1, 2, 3])

In [34]:
float_32_tensor*int_32_tensor

tensor([1., 4., 9.])

###Getting information from tensors:


1. To get shape of a tensor we use: 'tensor.shape'
2. To get dimension of tensor we use: 'tensor.ndim'
3. To get datatype from a tensor we use: 'tensor.dtype'



In [35]:
#Create a tensor:
example_tensor= torch.rand(2,4)
example_tensor

tensor([[0.8895, 0.1864, 0.9779, 0.8642],
        [0.9273, 0.0760, 0.4922, 0.5484]])

In [36]:
print(example_tensor)
print(f"Data type of example_tensor is: {example_tensor.dtype}")
print(f"Shape of example_tensor is: {example_tensor.shape}")
print(f"Dimension of example_tensor is: {example_tensor.ndim}")
print(f"Device example_tensor is on: {example_tensor.device}")

tensor([[0.8895, 0.1864, 0.9779, 0.8642],
        [0.9273, 0.0760, 0.4922, 0.5484]])
Data type of example_tensor is: torch.float32
Shape of example_tensor is: torch.Size([2, 4])
Dimension of example_tensor is: 2
Device example_tensor is on: cpu


###Manipulating Tensors: ---> just mathematical operations.


1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [37]:
#Addition:
TENSOR1= torch.tensor([1,2,3])
TENSOR1 + 10 #Remember here we are not actually creating a new Tensor1 we are just adding TENSOR1+10

tensor([11, 12, 13])

In [38]:
#similarly for multiplication:
TENSOR1*10

tensor([10, 20, 30])

###How can we use pytorch in these operations:
####Pytorch has inbuild math functions like:
torch.add
torch.mul

In [39]:
#

###Matrix Multiplication:
#####Two main ways for this multiplication
1.   Element-wise multiplication
2.   Matrix multiplication



In [40]:
#Element-wise multiplication:
print(TENSOR1, "*", TENSOR1)
print(f"Equals: {TENSOR1 * TENSOR1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
#Matrix multiplication:
torch.matmul(TENSOR1, TENSOR1)
#basically gives output something like 1*1+ 2*2+ 3*3

tensor(14)

###Why to use matrix multiplication inbuild instead of doing it by hand:

In [42]:
%%time
big_tensor= torch.rand(10000,10000)

CPU times: user 483 ms, sys: 162 ms, total: 646 ms
Wall time: 646 ms


In [52]:
%%time
big_tensor = torch.rand(10000, 10000,
                                         dtype=torch.float32, # or torch.float16, torch.long, etc.
                                         device='cuda',        # 'cpu' or 'cuda' if a GPU is available
                                         requires_grad=False) # True if you want to compute gradients for this tensor

CPU times: user 480 µs, sys: 0 ns, total: 480 µs
Wall time: 325 µs


In [53]:
#Matrix multiplication by hand:
%%time
value=0
for i in range(len(big_tensor)):
  value+= big_tensor[i]* big_tensor[i]
value

CPU times: user 220 ms, sys: 0 ns, total: 220 ms
Wall time: 220 ms


tensor([3329.6125, 3399.0706, 3293.2148,  ..., 3321.9951, 3352.0210,
        3276.8667], device='cuda:0')

In [54]:
#Matrix multiplication using pytorch inbuild function:
%%time
torch.matmul(big_tensor, big_tensor)

CPU times: user 537 µs, sys: 0 ns, total: 537 µs
Wall time: 314 µs


tensor([[2504.7622, 2562.5889, 2495.5183,  ..., 2519.9958, 2532.1560,
         2486.5837],
        [2506.6545, 2535.1909, 2485.1401,  ..., 2498.2046, 2495.4285,
         2474.1055],
        [2497.6162, 2549.3918, 2494.7690,  ..., 2488.1665, 2494.7468,
         2473.7131],
        ...,
        [2492.8430, 2545.7786, 2478.7231,  ..., 2485.5898, 2505.8081,
         2464.4524],
        [2495.5977, 2539.8015, 2487.1580,  ..., 2491.0994, 2502.7441,
         2476.6289],
        [2506.1658, 2529.1807, 2469.1309,  ..., 2504.3582, 2513.5881,
         2471.8772]], device='cuda:0')