<a href="https://colab.research.google.com/github/HelloSamved/learning-neural-network/blob/master/pytorch/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


##Introduction to Tensors
###creating tensors

Pytorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/2.12/tensors.html

In [2]:
##Introduction to Tensors:
#Creating tensors

In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#convert tensor back to integer
scalar.item()

7

In [6]:
#Vector:
vector= torch.tensor([10,7])
vector

tensor([10,  7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#####We can think of dimension as number of square brackets while defining inside torch.tensor()
#####And Shape depends on order which is for our vector is (2x1)

In [9]:
#Create a matrix:
MATRIX= torch.tensor([[1,2],[2,3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Create a tensor:
TENSOR= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Here 1 means that we got one (3x3) matrix

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR1= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1,3,5],
                        [2,4,6],
                        [7,8,9]]])

In [17]:
TENSOR1.ndim

3

In [18]:
TENSOR1.shape

torch.Size([2, 3, 3])

###Random tensors

##Random Tensors
####Why Random Tensors?
####Random tensors are important because they way neural network learn is that they start with tensors full numbers and then adjust those random numbers to better represent the data.

###The flow looks like:
####Start with random numbers in tensor --> look at data --> update random numbers --> look at data --> (loop)

In [19]:
#Create a random tensor of size:
random_tensor1= torch.rand(1,10,10)
random_tensor1

tensor([[[0.3645, 0.6789, 0.0072, 0.6078, 0.1155, 0.3040, 0.8711, 0.1862,
          0.7140, 0.8969],
         [0.7511, 0.7763, 0.5709, 0.2638, 0.8560, 0.0422, 0.4896, 0.4940,
          0.0564, 0.8685],
         [0.8639, 0.6278, 0.2154, 0.4800, 0.0578, 0.3852, 0.6190, 0.9549,
          0.6849, 0.4242],
         [0.2960, 0.2100, 0.5846, 0.4178, 0.8786, 0.1170, 0.1844, 0.2714,
          0.7017, 0.4611],
         [0.1743, 0.6925, 0.0719, 0.4504, 0.8818, 0.9046, 0.0233, 0.8138,
          0.9962, 0.9234],
         [0.7555, 0.2186, 0.1417, 0.4659, 0.9512, 0.7831, 0.3590, 0.8821,
          0.3859, 0.9579],
         [0.7153, 0.3780, 0.2817, 0.9187, 0.3717, 0.0049, 0.8924, 0.2530,
          0.8990, 0.2606],
         [0.6979, 0.6002, 0.8585, 0.9972, 0.8046, 0.3095, 0.2918, 0.8760,
          0.4863, 0.6776],
         [0.9631, 0.0569, 0.8111, 0.1296, 0.2908, 0.0981, 0.9914, 0.5904,
          0.8052, 0.7164],
         [0.5440, 0.3866, 0.3946, 0.6313, 0.2365, 0.1783, 0.2354, 0.2193,
          0.6032,

In [20]:
random_tensor1.shape

torch.Size([1, 10, 10])

In [21]:
random_tensor2= torch.rand(4,10,10)
random_tensor2

tensor([[[0.0541, 0.8773, 0.6452, 0.3154, 0.5805, 0.3789, 0.1129, 0.8060,
          0.3256, 0.4788],
         [0.6540, 0.6659, 0.9518, 0.8245, 0.3712, 0.5549, 0.8288, 0.9942,
          0.3131, 0.6132],
         [0.6556, 0.7295, 0.1289, 0.1704, 0.1995, 0.7577, 0.1531, 0.1319,
          0.8406, 0.6708],
         [0.3643, 0.6527, 0.5107, 0.7470, 0.2423, 0.9291, 0.6290, 0.7751,
          0.6603, 0.4106],
         [0.2348, 0.6156, 0.0096, 0.2718, 0.7227, 0.2506, 0.8816, 0.8010,
          0.6927, 0.0880],
         [0.6342, 0.3576, 0.4800, 0.4084, 0.6546, 0.0776, 0.5267, 0.7859,
          0.3071, 0.1861],
         [0.1418, 0.5268, 0.3653, 0.4812, 0.5769, 0.6564, 0.4599, 0.6501,
          0.3961, 0.0973],
         [0.3490, 0.7553, 0.7758, 0.6792, 0.1365, 0.5143, 0.8791, 0.7083,
          0.8788, 0.9958],
         [0.2123, 0.3450, 0.7759, 0.5227, 0.6252, 0.2658, 0.5303, 0.3651,
          0.8506, 0.0043],
         [0.3361, 0.4942, 0.3323, 0.3210, 0.8088, 0.5639, 0.1365, 0.7250,
          0.8358,

In [22]:
random_tensor2.shape, random_tensor2.ndim

(torch.Size([4, 10, 10]), 3)

In [23]:
#Random tensor with similar shape to an image:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

##Zeroes and Ones

In [24]:
#Create a tensor with only zeroes:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create a tensor with only ones:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors like

In [26]:
#Use torch.arange()
one_to_ten=torch.arange(start=1, end= 100, step=5)
one_to_ten

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [27]:
one_to_ten.shape, one_to_ten.ndim

(torch.Size([20]), 1)

In [28]:
#Creating tensors like:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Data Types

In [29]:
#Float 32 Type:
float_32_tensor= torch.tensor([1.0,2.0,3.0],
                               dtype=None, #this defines the data type of the tensor, here none will set it dtype as float32 by default
                               device= "cuda", #
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.], device='cuda:0'), torch.float32)

In [31]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [43]:
#Just Experimenting
x= float_32_tensor* float_16_tensor
x

tensor([1., 4., 9.], device='cuda:0')

In [44]:
x.dtype

torch.float32