<a href="https://colab.research.google.com/github/HelloSamved/learning-neural-network/blob/master/pytorch/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


##Introduction to Tensors
###creating tensors

Pytorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/2.12/tensors.html

In [2]:
##Introduction to Tensors:
#Creating tensors

In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#convert tensor back to integer
scalar.item()

7

In [6]:
#Vector:
vector= torch.tensor([10,7])
vector

tensor([10,  7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#####We can think of dimension as number of square brackets while defining inside torch.tensor()
#####And Shape depends on order which is for our vector is (2x1)

In [9]:
#Create a matrix:
MATRIX= torch.tensor([[1,2],[2,3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Create a tensor:
TENSOR= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Here 1 means that we got one (3x3) matrix

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR1= torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1,3,5],
                        [2,4,6],
                        [7,8,9]]])

In [17]:
TENSOR1.ndim

3

In [18]:
TENSOR1.shape

torch.Size([2, 3, 3])

###Random tensors

##Random Tensors
####Why Random Tensors?
####Random tensors are important because they way neural network learn is that they start with tensors full numbers and then adjust those random numbers to better represent the data.

###The flow looks like:
####Start with random numbers in tensor --> look at data --> update random numbers --> look at data --> (loop)

In [19]:
#Create a random tensor of size:
random_tensor1= torch.rand(1,10,10)
random_tensor1

tensor([[[0.8028, 0.7244, 0.2520, 0.4670, 0.6131, 0.7115, 0.1007, 0.0224,
          0.5353, 0.6015],
         [0.1833, 0.8574, 0.1693, 0.8449, 0.0917, 0.3493, 0.2978, 0.0779,
          0.5421, 0.4483],
         [0.0439, 0.1064, 0.9373, 0.2666, 0.5276, 0.6014, 0.3515, 0.4080,
          0.4530, 0.4902],
         [0.0423, 0.4830, 0.1373, 0.3833, 0.3655, 0.3729, 0.8508, 0.6648,
          0.5287, 0.8982],
         [0.7333, 0.1565, 0.3593, 0.7041, 0.2141, 0.9423, 0.2902, 0.1678,
          0.1380, 0.3971],
         [0.0834, 0.0800, 0.8086, 0.5686, 0.6720, 0.6970, 0.3423, 0.2009,
          0.2036, 0.3474],
         [0.9277, 0.8695, 0.9896, 0.1616, 0.8211, 0.5368, 0.3267, 0.7773,
          0.1215, 0.3545],
         [0.1150, 0.6844, 0.2435, 0.3556, 0.2915, 0.7046, 0.0382, 0.0411,
          0.3299, 0.0187],
         [0.5612, 0.8006, 0.9841, 0.3252, 0.8581, 0.7665, 0.6776, 0.2575,
          0.8345, 0.1579],
         [0.0261, 0.9138, 0.7099, 0.4865, 0.6620, 0.2768, 0.1436, 0.4707,
          0.7620,

In [20]:
random_tensor1.shape

torch.Size([1, 10, 10])

In [21]:
random_tensor2= torch.rand(4,10,10)
random_tensor2

tensor([[[9.2074e-01, 3.0707e-01, 7.2497e-01, 7.0995e-02, 7.3694e-01,
          6.4240e-01, 4.3479e-01, 8.5660e-01, 9.7645e-01, 7.5540e-01],
         [4.9360e-01, 2.2473e-01, 2.7700e-01, 3.0040e-01, 3.8141e-02,
          9.2739e-01, 6.8576e-01, 9.9443e-01, 9.9440e-01, 6.2761e-01],
         [8.8119e-01, 4.2475e-01, 4.5951e-02, 3.9961e-01, 8.5691e-01,
          7.5821e-02, 3.9180e-01, 4.9389e-01, 6.1131e-01, 8.0856e-01],
         [6.2907e-01, 6.9295e-01, 2.1485e-02, 1.9241e-01, 2.5066e-01,
          1.6728e-01, 9.2493e-01, 1.0427e-01, 3.3008e-01, 3.6408e-01],
         [6.8373e-01, 8.0654e-01, 8.1795e-04, 7.8414e-01, 8.1557e-01,
          2.5284e-01, 6.0716e-01, 4.1259e-01, 1.7176e-01, 3.4936e-01],
         [5.4550e-01, 2.6032e-01, 6.7411e-01, 1.5093e-01, 8.1885e-02,
          7.6394e-01, 3.8138e-01, 8.9186e-01, 1.2381e-01, 5.0068e-01],
         [7.2173e-01, 9.1985e-01, 7.7161e-01, 3.1967e-03, 1.3289e-01,
          8.6092e-01, 6.6017e-01, 1.6556e-01, 7.0892e-01, 3.6628e-01],
         [5.5

In [22]:
random_tensor2.shape, random_tensor2.ndim

(torch.Size([4, 10, 10]), 3)

In [23]:
#Random tensor with similar shape to an image:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

##Zeroes and Ones

In [24]:
#Create a tensor with only zeroes:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create a tensor with only ones:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors like

In [26]:
#Use torch.arange()
one_to_ten=torch.arange(start=1, end= 100, step=5)
one_to_ten

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [27]:
one_to_ten.shape, one_to_ten.ndim

(torch.Size([20]), 1)

In [28]:
#Creating tensors like:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Data Types

In [29]:
#Float 32 Type:
float_32_tensor= torch.tensor([1.0,2.0,3.0],
                               dtype=None, #this defines the data type of the tensor, here none will set it dtype as float32 by default
                               device= None, #
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [30]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [31]:
#Just Experimenting
x= float_32_tensor* float_16_tensor
x

tensor([1., 4., 9.])

In [32]:
x.dtype

torch.float32

In [33]:
int_32_tensor= torch.tensor([1,2,3], dtype= torch.long)
int_32_tensor

tensor([1, 2, 3])

In [34]:
float_32_tensor*int_32_tensor

tensor([1., 4., 9.])

###Getting information from tensors:


1. To get shape of a tensor we use: 'tensor.shape'
2. To get dimension of tensor we use: 'tensor.ndim'
3. To get datatype from a tensor we use: 'tensor.dtype'



In [35]:
#Create a tensor:
example_tensor= torch.rand(2,4)
example_tensor

tensor([[0.6013, 0.0243, 0.8518, 0.0502],
        [0.0068, 0.3228, 0.5399, 0.5123]])

In [36]:
print(example_tensor)
print(f"Data type of example_tensor is: {example_tensor.dtype}")
print(f"Shape of example_tensor is: {example_tensor.shape}")
print(f"Dimension of example_tensor is: {example_tensor.ndim}")
print(f"Device example_tensor is on: {example_tensor.device}")

tensor([[0.6013, 0.0243, 0.8518, 0.0502],
        [0.0068, 0.3228, 0.5399, 0.5123]])
Data type of example_tensor is: torch.float32
Shape of example_tensor is: torch.Size([2, 4])
Dimension of example_tensor is: 2
Device example_tensor is on: cpu


###Manipulating Tensors: ---> just mathematical operations.


1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [37]:
#Addition:
TENSOR1= torch.tensor([1,2,3])
TENSOR1 + 10 #Remember here we are not actually creating a new Tensor1 we are just adding TENSOR1+10

tensor([11, 12, 13])

In [38]:
#similarly for multiplication:
TENSOR1*10

tensor([10, 20, 30])

###How can we use pytorch in these operations:
####Pytorch has inbuild math functions like:
torch.add
torch.mul

In [39]:
#

###Matrix Multiplication:
#####Two main ways for this multiplication
1.   Element-wise multiplication
2.   Matrix multiplication



In [40]:
#Element-wise multiplication:
print(TENSOR1, "*", TENSOR1)
print(f"Equals: {TENSOR1 * TENSOR1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
#Matrix multiplication:
torch.matmul(TENSOR1, TENSOR1)
#basically gives output something like 1*1+ 2*2+ 3*3

tensor(14)

###Why to use matrix multiplication inbuild instead of doing it by hand:

In [42]:
%%time
big_tensor= torch.rand(10000,10000)

CPU times: user 505 ms, sys: 158 ms, total: 663 ms
Wall time: 664 ms


In [43]:
%%time
big_tensor = torch.rand(10000, 10000,
                                         dtype=torch.float32, # or torch.float16, torch.long, etc.
                                         device='cuda',        # 'cpu' or 'cuda' if a GPU is available
                                         requires_grad=False) # True if you want to compute gradients for this tensor

CPU times: user 33.7 ms, sys: 304 ms, total: 338 ms
Wall time: 408 ms


In [53]:
#Matrix multiplication by hand:
%%time
value=0
for i in range(len(big_tensor)):
  value+= big_tensor[i]* big_tensor[i]
value

CPU times: user 288 ms, sys: 0 ns, total: 288 ms
Wall time: 292 ms


tensor([3323.2239, 3303.8584, 3311.6621,  ..., 3320.1196, 3376.2163,
        3379.7896], device='cuda:0')

In [54]:
#Matrix multiplication using pytorch inbuild function:
%%time
torch.matmul(big_tensor, big_tensor)

CPU times: user 179 µs, sys: 900 µs, total: 1.08 ms
Wall time: 659 µs


tensor([[2505.4688, 2509.2537, 2496.8374,  ..., 2510.6716, 2538.0508,
         2549.2996],
        [2499.9211, 2514.8892, 2494.9312,  ..., 2513.2629, 2548.8584,
         2531.0391],
        [2480.5286, 2478.3872, 2479.0547,  ..., 2483.7424, 2519.6521,
         2528.1785],
        ...,
        [2498.5017, 2517.1902, 2515.0728,  ..., 2515.5239, 2555.4849,
         2542.3176],
        [2483.4763, 2482.1846, 2471.6272,  ..., 2475.9453, 2510.4822,
         2518.2148],
        [2503.0540, 2498.7234, 2501.9761,  ..., 2493.1519, 2530.6624,
         2525.0339]], device='cuda:0')

##Shape Errors

In [58]:
TENSORA= torch.tensor([[1,2],
                       [2,3],
                       [3,4]])
TENSORB= torch.tensor([[5,6],
                       [6,7],
                       [7,8]])

torch.mm(TENSORA, TENSORB) #.mm means matmul (alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

##Transpose
####To fix the upper error, due to the shape of the matrix.

In [59]:
torch.mm(TENSORA, TENSORB.T) #TENSORB.T --> here .T means transposing the TENSORB

tensor([[17, 20, 23],
        [28, 33, 38],
        [39, 46, 53]])

###Min, Max, Mean and Sum of a TENSOR

In [71]:
#creating a tensor:
x= torch.arange(0,100,11)
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [61]:
#To find the min:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
#To find the max:
torch.max(x), x.max()

(tensor(140), tensor(140))

In [66]:
#To change the datatype of x so that mean function can work on it
x= x.type(torch.float32)

In [67]:
#To find the mean:
#mean function --> torch.mean(x) will not work on x if x is an int64 type because int64 is in Long format
torch.mean(x)

tensor(70.)

In [72]:
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [74]:
#To find the posistion in tensor where minimum value lies: to find this we use "argmin()"
x.argmin()

tensor(0)

In [75]:
x[0]

tensor(0)

In [76]:
#To find the posistion in tensor where maximum value lies: to find this we use "argmin()"
x.argmax()

tensor(9)

In [77]:
x[9]

tensor(99)

##Reshaping, stacking, squeezing and unsqueezing tensors:
* Reshaping- Reshapes an input tensor to a defined shape so that we can perform our desired mathematically operations on it.
* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking- Combine multiple tensors on top of each other.
* Squeeze- removes all '1' dimensions from a tensor
* Unsqeeze- add a '1' dimension to a target tensor
* Permute- Return a view of the input with dimensions permuted (swapped) in a certain way.

In [82]:
#Create a tensor:
x= torch.arange(1.,10.)
y= torch.arange(1., 10.)
x, x.shape, y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [85]:
#Add an extra dimension:
x_reshaped= x.reshape(1,9) #here shape of x is 9 so values in our bracket could be anything until there multiplication =9, here 1*9=9, we can also write (3,3), since 3*3=9

#same multiplication condition also goes with y
y_transpose_reshaped= y.reshape(9,1)
x_reshaped, x_reshaped.shape, y_transpose_reshaped, y_transpose_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [86]:
x_reshaped==y_transpose_reshaped

tensor([[ True, False, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False],
        [False, False, False, False,  True, False, False, False, False],
        [False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False, False,  True]])

In [87]:
x_reshaped==y_transpose_reshaped.T

tensor([[True, True, True, True, True, True, True, True, True]])

In [94]:
#Stack Tensors on top of each other:
x_stacked= torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [97]:
# Torch.squeeze:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [103]:
x_reshaped.shape

torch.Size([1, 9])

In [111]:
x_squeezed=x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [108]:
x_reshaped.squeeze().shape

torch.Size([9])

In [112]:
#Torch.unsqueeze:
x_unsqueezed= x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [113]:
#Torch.permute- rearranges the dimension of the target tensor in a specified order:
x_original= torch.rand(size=(224,224,3))
x_original

tensor([[[8.0581e-01, 4.1852e-01, 4.2076e-01],
         [5.9468e-01, 2.0975e-02, 8.3055e-01],
         [3.0422e-02, 2.8451e-01, 2.6199e-03],
         ...,
         [3.3034e-01, 4.0582e-01, 7.7294e-01],
         [6.8222e-01, 2.0671e-01, 7.8334e-01],
         [6.0118e-01, 1.4136e-01, 9.2852e-01]],

        [[3.6005e-01, 4.6503e-01, 4.0299e-02],
         [4.8264e-01, 8.6001e-01, 1.0787e-01],
         [7.5475e-01, 7.1740e-01, 8.8520e-02],
         ...,
         [7.7019e-02, 7.3183e-01, 2.9091e-02],
         [7.6653e-01, 7.5448e-01, 8.9010e-01],
         [9.4255e-01, 9.9701e-01, 1.9761e-01]],

        [[1.0562e-01, 7.6901e-01, 8.7428e-01],
         [4.1646e-01, 3.4128e-01, 5.9213e-01],
         [8.4485e-01, 7.3945e-01, 7.6515e-01],
         ...,
         [4.6547e-01, 3.4703e-01, 1.4927e-01],
         [6.9182e-01, 1.2205e-01, 6.1723e-01],
         [6.0788e-02, 8.9714e-01, 6.7832e-01]],

        ...,

        [[9.2958e-02, 3.8616e-01, 9.6456e-01],
         [3.1854e-01, 7.0942e-01, 5.5282e-01]

In [116]:
#permuting the original tensor x_original:
x_permuted= x_original.permute(2,0,1)
print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")


Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])
